import 'dotenv/config';
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '../generated/prisma/client';

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});

const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function ensureDemoCoach() {
  return prisma.coach.upsert({
    where: { email: 'demo@footballcoach.local' },
    update: {},
    create: {
      email: 'demo@footballcoach.local',
      password: 'demo-password',
      name: 'Demo Coach',
      club: 'Demo Club',
    },
  });
}

async function main() {
  console.log('Seeding drills...');

  const demoCoach = await ensureDemoCoach();

  const drills = [
    // -----------------------------------
    // 4–6 år
    // -----------------------------------
    {
      id: 'ball-familiarity-4-6',
      name: 'Ball Familiarity',
      description:
        'Simple ball mastery with lots of touches using both feet.',
      objectives: 'Comfort with the ball, coordination, fun',
      category: 'warmup',
      focusTags: 'ball control, coordination, fun',
      difficulty: 1,
      minPlayers: 4,
      maxPlayers: 20,
      durationMin: 10,
      intensity: 1,
      equipment: 'Balls, cones',
      pitchArea: '10x10',
      ageMin: 4,
      ageMax: 6,
      coachId: demoCoach.id,
    },
    {
      id: 'red-light-green-light',
      name: 'Red Light Green Light',
      description:
        'Players dribble freely and stop or go based on coach commands.',
      objectives: 'Dribbling, listening, stopping and starting',
      category: 'warmup',
      focusTags: 'dribbling, fun, coordination',
      difficulty: 1,
      minPlayers: 4,
      maxPlayers: 20,
      durationMin: 10,
      intensity: 1,
      equipment: 'Balls, cones',
      pitchArea: '12x12',
      ageMin: 4,
      ageMax: 7,
      coachId: demoCoach.id,
    },
    {
      id: 'animal-dribbling',
      name: 'Animal Dribbling',
      description:
        'Players dribble the ball and imitate different animals on coach command.',
      objectives: 'Movement variety, ball control, fun',
      category: 'technical',
      focusTags: 'dribbling, fun, movement',
      difficulty: 1,
      minPlayers: 4,
      maxPlayers: 16,
      durationMin: 12,
      intensity: 1,
      equipment: 'Balls, cones',
      pitchArea: '12x12',
      ageMin: 4,
      ageMax: 7,
      coachId: demoCoach.id,
    },
    {
      id: 'treasure-hunt-dribbling',
      name: 'Treasure Hunt Dribbling',
      description:
        'Players dribble to collect cones or objects and bring them back to base.',
      objectives: 'Ball control, fun, awareness',
      category: 'technical',
      focusTags: 'dribbling, fun, coordination',
      difficulty: 1,
      minPlayers: 4,
      maxPlayers: 16,
      durationMin: 10,
      intensity: 1,
      equipment: 'Balls, cones, bibs',
      pitchArea: '12x12',
      ageMin: 4,
      ageMax: 7,
      coachId: demoCoach.id,
    },
    {
      id: 'simple-1v1-to-goal',
      name: 'Simple 1v1 to Goal',
      description:
        'Very simple 1v1 game toward mini goals with lots of encouragement.',
      objectives: 'Confidence, attacking, basic defending',
      category: 'game',
      focusTags: '1v1, confidence, attacking, fun',
      difficulty: 1,
      minPlayers: 4,
      maxPlayers: 12,
      durationMin: 12,
      intensity: 2,
      equipment: 'Balls, bibs, mini goals',
      pitchArea: '15x10',
      ageMin: 5,
      ageMax: 8,
      coachId: demoCoach.id,
    },
    {
      id: 'small-sided-3v3-young',
      name: 'Small-Sided 3v3',
      description:
        'Simple 3v3 free play with minimal rules.',
      objectives: 'Enjoyment, ball contact, basic game understanding',
      category: 'game',
      focusTags: 'game, fun, confidence',
      difficulty: 1,
      minPlayers: 6,
      maxPlayers: 10,
      durationMin: 15,
      intensity: 2,
      equipment: 'Balls, bibs, mini goals',
      pitchArea: '20x15',
      ageMin: 5,
      ageMax: 8,
      coachId: demoCoach.id,
    },

    // -----------------------------------
    // 5–8 år
    // -----------------------------------
    {
      id: 'gate-dribbling-young',
      name: 'Gate Dribbling',
      description:
        'Players dribble through as many gates as possible in the area.',
      objectives: 'Close control, awareness, changing direction',
      category: 'technical',
      focusTags: 'dribbling, scanning, ball control',
      difficulty: 1,
      minPlayers: 4,
      maxPlayers: 16,
      durationMin: 12,
      intensity: 1,
      equipment: 'Balls, cones',
      pitchArea: '15x15',
      ageMin: 5,
      ageMax: 8,
      coachId: demoCoach.id,
    },
    {
      id: 'traffic-light-turns',
      name: 'Traffic Light Turns',
      description:
        'Players dribble and perform turns on coach signal.',
      objectives: 'Turning, dribbling, reaction',
      category: 'technical',
      focusTags: 'dribbling, turns, coordination',
      difficulty: 1,
      minPlayers: 4,
      maxPlayers: 16,
      durationMin: 10,
      intensity: 1,
      equipment: 'Balls, cones',
      pitchArea: '12x12',
      ageMin: 5,
      ageMax: 8,
      coachId: demoCoach.id,
    },
    {
      id: 'passing-through-gates',
      name: 'Passing Through Gates',
      description:
        'Pairs pass through small cone gates while moving around the area.',
      objectives: 'Basic passing, receiving, accuracy',
      category: 'technical',
      focusTags: 'passing, first touch, fun',
      difficulty: 1,
      minPlayers: 4,
      maxPlayers: 16,
      durationMin: 10,
      intensity: 1,
      equipment: 'Balls, cones',
      pitchArea: '15x15',
      ageMin: 6,
      ageMax: 9,
      coachId: demoCoach.id,
    },
    {
      id: 'numbers-game-2v2',
      name: 'Numbers Game 2v2',
      description:
        'Coach calls numbers and players enter for a quick 2v2 game.',
      objectives: 'Reaction, confidence, basic decisions',
      category: 'game',
      focusTags: 'game, reaction, confidence, decision making',
      difficulty: 2,
      minPlayers: 6,
      maxPlayers: 12,
      durationMin: 12,
      intensity: 2,
      equipment: 'Balls, bibs, mini goals',
      pitchArea: '20x15',
      ageMin: 6,
      ageMax: 9,
      coachId: demoCoach.id,
    },

    // -----------------------------------
    // 8–12 år
    // -----------------------------------
    {
      id: 'rondo-5v2',
      name: 'Rondo 5v2',
      description:
        'Five attackers keep possession against two defenders in a tight area.',
      objectives: 'Scanning, quick passing, first touch under pressure',
      category: 'warmup',
      focusTags: 'passing, first touch, scanning, possession',
      difficulty: 2,
      minPlayers: 7,
      maxPlayers: 10,
      durationMin: 10,
      intensity: 1,
      equipment: 'Balls, cones, bibs',
      pitchArea: '12x12',
      ageMin: 8,
      ageMax: 18,
      coachId: demoCoach.id,
    },
    {
      id: 'triangle-passing',
      name: 'Triangle Passing',
      description:
        'Players pass and move in triangles with emphasis on body shape and timing.',
      objectives: 'Pass quality, movement after pass, receiving angles',
      category: 'technical',
      focusTags: 'passing, first touch, movement',
      difficulty: 2,
      minPlayers: 6,
      maxPlayers: 12,
      durationMin: 10,
      intensity: 1,
      equipment: 'Balls, cones',
      pitchArea: '15x15',
      ageMin: 8,
      ageMax: 18,
      coachId: demoCoach.id,
    },
    {
      id: 'passing-square-rotation',
      name: 'Passing Square Rotation',
      description:
        'Players pass around a square and rotate positions after passing.',
      objectives: 'Passing quality, receiving on the move, orientation',
      category: 'technical',
      focusTags: 'passing, first touch, movement, scanning',
      difficulty: 2,
      minPlayers: 6,
      maxPlayers: 12,
      durationMin: 10,
      intensity: 1,
      equipment: 'Balls, cones',
      pitchArea: '18x18',
      ageMin: 8,
      ageMax: 16,
      coachId: demoCoach.id,
    },
    {
      id: 'first-touch-under-pressure',
      name: 'First Touch Under Pressure',
      description:
        'Players receive passes while a defender applies controlled pressure.',
      objectives: 'First touch away from pressure, awareness before receiving',
      category: 'technical',
      focusTags: 'first touch, pressure, receiving, scanning',
      difficulty: 3,
      minPlayers: 6,
      maxPlayers: 12,
      durationMin: 12,
      intensity: 2,
      equipment: 'Balls, cones, bibs',
      pitchArea: '18x12',
      ageMin: 9,
      ageMax: 18,
      coachId: demoCoach.id,
    },
    {
      id: 'receiving-across-body',
      name: 'Receiving Across Body',
      description:
        'Players receive from one side and play out on the opposite side under limited pressure.',
      objectives: 'Body shape, first touch, awareness',
      category: 'technical',
      focusTags: 'first touch, body shape, passing, scanning',
      difficulty: 2,
      minPlayers: 6,
      maxPlayers: 12,
      durationMin: 10,
      intensity: 2,
      equipment: 'Balls, cones, mannequins',
      pitchArea: '18x15',
      ageMin: 9,
      ageMax: 16,
      coachId: demoCoach.id,
    },
    {
      id: '4v2-possession-box',
      name: '4v2 Possession Box',
      description:
        'Four attackers keep possession against two defenders in a defined grid.',
      objectives: 'Support angles, tempo, quick decision making',
      category: 'possession',
      focusTags: 'possession, passing, scanning, support',
      difficulty: 3,
      minPlayers: 6,
      maxPlayers: 10,
      durationMin: 12,
      intensity: 2,
      equipment: 'Balls, cones, bibs',
      pitchArea: '16x16',
      ageMin: 9,
      ageMax: 18,
      coachId: demoCoach.id,
    },
    {
      id: 'possession-with-targets',
      name: 'Possession With Targets',
      description:
        'Teams keep possession and score by finding target players.',
      objectives: 'Possession, support, decision making',
      category: 'possession',
      focusTags: 'possession, passing, decision making, support',
      difficulty: 3,
      minPlayers: 8,
      maxPlayers: 12,
      durationMin: 14,
      intensity: 2,
      equipment: 'Balls, cones, bibs',
      pitchArea: '24x18',
      ageMin: 10,
      ageMax: 18,
      coachId: demoCoach.id,
    },
    {
      id: '1v1-attacking-duel',
      name: '1v1 Attacking Duel',
      description:
        'Players attack defenders in isolated 1v1 situations toward goal.',
      objectives: 'Confidence, dribbling, attacking intent',
      category: 'technical',
      focusTags: 'dribbling, confidence, attacking',
      difficulty: 3,
      minPlayers: 4,
      maxPlayers: 10,
      durationMin: 10,
      intensity: 2,
      equipment: 'Balls, cones, mini goals',
      pitchArea: '15x10',
      ageMin: 8,
      ageMax: 18,
      coachId: demoCoach.id,
    },
    {
      id: '2v1-attack-channel',
      name: '2v1 Attack Channel',
      description:
        'Two attackers combine against one defender in a narrow channel.',
      objectives: 'Decision making, timing of pass, attacking support',
      category: 'game',
      focusTags: 'attack, passing, decision making',
      difficulty: 2,
      minPlayers: 6,
      maxPlayers: 12,
      durationMin: 10,
      intensity: 2,
      equipment: 'Balls, bibs, mini goals',
      pitchArea: '20x10',
      ageMin: 8,
      ageMax: 14,
      coachId: demoCoach.id,
    },
    {
      id: 'finishing-from-cutbacks',
      name: 'Finishing From Cutbacks',
      description:
        'Wide player serves cutbacks for arriving attackers finishing in the box.',
      objectives: 'Timing of runs, finishing technique, composure',
      category: 'finishing',
      focusTags: 'finishing, movement, timing',
      difficulty: 3,
      minPlayers: 6,
      maxPlayers: 12,
      durationMin: 12,
      intensity: 2,
      equipment: 'Balls, cones, goals',
      pitchArea: 'Penalty area',
      ageMin: 10,
      ageMax: 18,
      coachId: demoCoach.id,
    },
    {
      id: 'finishing-first-time',
      name: 'Finishing First Time',
      description:
        'Players attack service and finish first time from central and wide areas.',
      objectives: 'Finishing, timing, movement into box',
      category: 'finishing',
      focusTags: 'finishing, timing, movement',
      difficulty: 3,
      minPlayers: 6,
      maxPlayers: 12,
      durationMin: 12,
      intensity: 2,
      equipment: 'Balls, cones, goals',
      pitchArea: 'Final third',
      ageMin: 10,
      ageMax: 18,
      coachId: demoCoach.id,
    },
    {
      id: 'small-sided-game-4v4',
      name: 'Small-Sided Game 4v4',
      description:
        'Fast 4v4 game with high involvement and many touches.',
      objectives: 'Decision making, positioning, transition, confidence',
      category: 'game',
      focusTags: 'game, decision making, positioning, transition',
      difficulty: 3,
      minPlayers: 8,
      maxPlayers: 12,
      durationMin: 15,
      intensity: 2,
      equipment: 'Balls, bibs, goals',
      pitchArea: '25x20',
      ageMin: 8,
      ageMax: 15,
      coachId: demoCoach.id,
    },

    // -----------------------------------
    // 10–18 år
    // -----------------------------------
    {
      id: '5v5-possession-game',
      name: '5v5 Possession Game',
      description:
        'Small-sided game with a strong focus on keeping the ball and creating angles.',
      objectives: 'Possession, support play, tempo, patience',
      category: 'possession',
      focusTags: 'possession, passing, decision making',
      difficulty: 4,
      minPlayers: 10,
      maxPlayers: 12,
      durationMin: 15,
      intensity: 2,
      equipment: 'Balls, cones, bibs',
      pitchArea: '25x20',
      ageMin: 10,
      ageMax: 18,
      coachId: demoCoach.id,
    },
    {
      id: 'transition-4v4',
      name: 'Transition 4v4',
      description:
        'Small-sided transition game with immediate attack after regaining possession.',
      objectives: 'Transition, reactions, decision making',
      category: 'game',
      focusTags: 'transition, decision making, intensity',
      difficulty: 4,
      minPlayers: 8,
      maxPlayers: 10,
      durationMin: 15,
      intensity: 3,
      equipment: 'Balls, cones, bibs, mini goals',
      pitchArea: '30x20',
      ageMin: 11,
      ageMax: 18,
      coachId: demoCoach.id,
    },
    {
      id: '3v2-attack-to-goal',
      name: '3v2 Attack to Goal',
      description:
        'Three attackers combine quickly against two defenders to finish.',
      objectives: 'Final third decisions, timing, finishing',
      category: 'game',
      focusTags: 'finishing, passing, decision making, attack',
      difficulty: 4,
      minPlayers: 5,
      maxPlayers: 12,
      durationMin: 12,
      intensity: 3,
      equipment: 'Balls, cones, goal',
      pitchArea: 'Half pitch',
      ageMin: 10,
      ageMax: 18,
      coachId: demoCoach.id,
    },
    {
      id: 'small-sided-game-6v6',
      name: 'Small-Sided Game 6v6',
      description:
        'Conditioned game to encourage realistic decisions and high involvement.',
      objectives: 'Transfer to game, positioning, communication',
      category: 'game',
      focusTags: 'game, positioning, decision making, intensity',
      difficulty: 4,
      minPlayers: 10,
      maxPlayers: 14,
      durationMin: 20,
      intensity: 3,
      equipment: 'Balls, bibs, goals',
      pitchArea: '40x30',
      ageMin: 10,
      ageMax: 18,
      coachId: demoCoach.id,
    },
    {
      id: 'positional-game-6v4',
      name: 'Positional Game 6v4',
      description:
        'Team in possession works on spacing and playing through lines.',
      objectives: 'Positioning, scanning, support angles, playing through pressure',
      category: 'possession',
      focusTags: 'positioning, possession, scanning, passing',
      difficulty: 4,
      minPlayers: 10,
      maxPlayers: 14,
      durationMin: 16,
      intensity: 2,
      equipment: 'Balls, bibs, cones',
      pitchArea: '30x25',
      ageMin: 12,
      ageMax: 18,
      coachId: demoCoach.id,
    },
    {
      id: 'defensive-shape-6v6',
      name: 'Defensive Shape 6v6',
      description:
        'Team works on compactness, distances and pressing cues in a conditioned game.',
      objectives: 'Defensive organization, communication, compactness',
      category: 'game',
      focusTags: 'defending, positioning, communication, pressing',
      difficulty: 4,
      minPlayers: 10,
      maxPlayers: 14,
      durationMin: 16,
      intensity: 3,
      equipment: 'Balls, bibs, cones, goals',
      pitchArea: '40x30',
      ageMin: 12,
      ageMax: 18,
      coachId: demoCoach.id,
    },
    {
      id: 'pressing-triggers-game',
      name: 'Pressing Triggers Game',
      description:
        'Conditioned game focusing on pressing cues and coordinated pressure.',
      objectives: 'Pressing, communication, collective timing',
      category: 'game',
      focusTags: 'pressing, transition, decision making, communication',
      difficulty: 5,
      minPlayers: 10,
      maxPlayers: 16,
      durationMin: 18,
      intensity: 3,
      equipment: 'Balls, bibs, goals',
      pitchArea: '45x35',
      ageMin: 13,
      ageMax: 18,
      coachId: demoCoach.id,
    },
    {
      id: 'build-up-under-pressure',
      name: 'Build-up Under Pressure',
      description:
        'Team plays out from the back against an organized press.',
      objectives: 'Build-up, composure, positioning, decision making',
      category: 'technical',
      focusTags: 'build up, passing, decision making, positioning',
      difficulty: 5,
      minPlayers: 10,
      maxPlayers: 18,
      durationMin: 18,
      intensity: 3,
      equipment: 'Balls, bibs, mannequins, goals',
      pitchArea: 'Half pitch',
      ageMin: 13,
      ageMax: 18,
      coachId: demoCoach.id,
    },
    {
      id: 'third-man-combination-play',
      name: 'Third Man Combination Play',
      description:
        'Players combine using wall passes and third-player runs to break lines.',
      objectives: 'Combination play, timing, breaking lines',
      category: 'technical',
      focusTags: 'passing, movement, decision making, attack',
      difficulty: 4,
      minPlayers: 6,
      maxPlayers: 14,
      durationMin: 14,
      intensity: 2,
      equipment: 'Balls, cones, mannequins',
      pitchArea: '25x20',
      ageMin: 12,
      ageMax: 18,
      coachId: demoCoach.id,
    },
    {
      id: 'finishing-under-pressure',
      name: 'Finishing Under Pressure',
      description:
        'Attackers finish quickly while defenders recover and apply pressure.',
      objectives: 'Composure, speed of execution, finishing decisions',
      category: 'finishing',
      focusTags: 'finishing, pressure, decision making',
      difficulty: 4,
      minPlayers: 6,
      maxPlayers: 12,
      durationMin: 14,
      intensity: 3,
      equipment: 'Balls, cones, goals, bibs',
      pitchArea: 'Final third',
      ageMin: 12,
      ageMax: 18,
      coachId: demoCoach.id,
    },
    {
      id: 'counter-attack-wave',
      name: 'Counter Attack Wave',
      description:
        'Teams attack quickly in waves after regaining possession.',
      objectives: 'Transition speed, final pass, decision making',
      category: 'game',
      focusTags: 'transition, attack, passing, decision making',
      difficulty: 4,
      minPlayers: 8,
      maxPlayers: 16,
      durationMin: 15,
      intensity: 3,
      equipment: 'Balls, cones, bibs, goals',
      pitchArea: 'Half pitch',
      ageMin: 12,
      ageMax: 18,
      coachId: demoCoach.id,
    },
    {
      id: 'overload-to-finish',
      name: 'Overload to Finish',
      description:
        'Attacking unit creates overloads in the final third and finishes quickly.',
      objectives: 'Creating superiority, final action, timing of support',
      category: 'finishing',
      focusTags: 'finishing, attack, overload, passing',
      difficulty: 4,
      minPlayers: 8,
      maxPlayers: 14,
      durationMin: 14,
      intensity: 3,
      equipment: 'Balls, bibs, goals',
      pitchArea: 'Final third',
      ageMin: 12,
      ageMax: 18,
      coachId: demoCoach.id,
    },
  ];

  for (const drill of drills) {
    await prisma.drill.upsert({
      where: { id: drill.id },
      update: drill,
      create: drill,
    });
  }

  console.log(`Seeded ${drills.length} drills successfully.`);
}

main()
  .catch((error) => {
    console.error('Seed failed:', error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });