import 'dotenv/config';
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '../generated/prisma/client';

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});

const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function ensureDemoCoach() {
  return prisma.coach.upsert({
    where: { email: 'demo@footballcoach.local' },
    update: {},
    create: {
      email: 'demo@footballcoach.local',
      password: 'demo-password',
      name: 'Demo Coach',
      club: 'Demo Club',
    },
  });
}

async function main() {
  console.log('Seeding full drill library...');

  const demoCoach = await ensureDemoCoach();

  const drills = [
    // =========================
    // WARMUP
    // =========================
    {
      id: 'warmup-ball-familiarity',
      name: 'Ball Familiarity',
      description: 'Players perform simple ball mastery touches using both feet.',
      objectives: 'Comfort with the ball, coordination, enjoyment',
      category: 'warmup',
      focusTags: 'ball control, coordination, fun',
      difficulty: 1,
      minPlayers: 4,
      maxPlayers: 20,
      durationMin: 10,
      intensity: 1,
      equipment: 'Balls, cones',
      pitchArea: '10x10',
      ageMin: 4,
      ageMax: 8,
      imageUrl: '/drills/warmup.png',
      coachId: demoCoach.id,
    },
    {
      id: 'warmup-red-light-green-light',
      name: 'Red Light Green Light',
      description: 'Players dribble and react to coach commands to stop and go.',
      objectives: 'Dribbling, listening, coordination',
      category: 'warmup',
      focusTags: 'dribbling, reaction, coordination',
      difficulty: 1,
      minPlayers: 4,
      maxPlayers: 20,
      durationMin: 10,
      intensity: 1,
      equipment: 'Balls, cones',
      pitchArea: '12x12',
      ageMin: 4,
      ageMax: 7,
      imageUrl: '/drills/warmup.png',
      coachId: demoCoach.id,
    },
    {
      id: 'warmup-animal-dribbling',
      name: 'Animal Dribbling',
      description: 'Players dribble and imitate different animal movements on command.',
      objectives: 'Movement variety, balance, fun',
      category: 'warmup',
      focusTags: 'dribbling, fun, movement',
      difficulty: 1,
      minPlayers: 4,
      maxPlayers: 16,
      durationMin: 10,
      intensity: 1,
      equipment: 'Balls, cones',
      pitchArea: '12x12',
      ageMin: 4,
      ageMax: 7,
      imageUrl: '/drills/warmup.png',
      coachId: demoCoach.id,
    },
    {
      id: 'warmup-gate-dribbling',
      name: 'Gate Dribbling',
      description: 'Players dribble through as many cone gates as possible.',
      objectives: 'Close control, awareness, turning',
      category: 'warmup',
      focusTags: 'dribbling, awareness, coordination',
      difficulty: 1,
      minPlayers: 4,
      maxPlayers: 16,
      durationMin: 10,
      intensity: 1,
      equipment: 'Balls, cones',
      pitchArea: '15x15',
      ageMin: 5,
      ageMax: 10,
      imageUrl: '/drills/warmup.png',
      coachId: demoCoach.id,
    },
    {
      id: 'warmup-pair-passing',
      name: 'Pair Passing Activation',
      description: 'Players pass in pairs while moving lightly around the area.',
      objectives: 'Activation, basic passing rhythm, communication',
      category: 'warmup',
      focusTags: 'passing, activation, communication',
      difficulty: 1,
      minPlayers: 4,
      maxPlayers: 20,
      durationMin: 8,
      intensity: 1,
      equipment: 'Balls, cones',
      pitchArea: '15x15',
      ageMin: 6,
      ageMax: 18,
      imageUrl: '/drills/warmup.png',
      coachId: demoCoach.id,
    },
    {
      id: 'warmup-dynamic-ball-warmup',
      name: 'Dynamic Ball Warm-Up',
      description: 'Players combine dynamic movement patterns with simple touches on the ball.',
      objectives: 'Raise body temperature, coordination, ball familiarity',
      category: 'warmup',
      focusTags: 'movement, coordination, ball control',
      difficulty: 1,
      minPlayers: 6,
      maxPlayers: 20,
      durationMin: 10,
      intensity: 1,
      equipment: 'Balls, cones',
      pitchArea: '15x15',
      ageMin: 8,
      ageMax: 18,
      imageUrl: '/drills/warmup.png',
      coachId: demoCoach.id,
    },
    {
      id: 'warmup-rondo-4v1',
      name: 'Rondo 4v1 Warm-Up',
      description: 'Four attackers keep possession against one defender in a small square.',
      objectives: 'Passing sharpness, scanning, first touch',
      category: 'warmup',
      focusTags: 'passing, first touch, scanning, possession',
      difficulty: 2,
      minPlayers: 5,
      maxPlayers: 8,
      durationMin: 10,
      intensity: 1,
      equipment: 'Balls, cones, bibs',
      pitchArea: '10x10',
      ageMin: 8,
      ageMax: 18,
      imageUrl: '/drills/rondo.png',
      coachId: demoCoach.id,
    },
    {
      id: 'warmup-rondo-5v2',
      name: 'Rondo 5v2 Warm-Up',
      description: 'Five attackers circulate the ball against two defenders.',
      objectives: 'Scanning, support angles, quick passing',
      category: 'warmup',
      focusTags: 'passing, scanning, support, possession',
      difficulty: 2,
      minPlayers: 7,
      maxPlayers: 10,
      durationMin: 10,
      intensity: 1,
      equipment: 'Balls, cones, bibs',
      pitchArea: '12x12',
      ageMin: 8,
      ageMax: 18,
      imageUrl: '/drills/rondo.png',
      coachId: demoCoach.id,
    },
    {
      id: 'warmup-mirror-movement',
      name: 'Mirror Movement',
      description: 'Players work in pairs mirroring each other with and without the ball.',
      objectives: 'Footwork, coordination, reaction',
      category: 'warmup',
      focusTags: 'movement, reaction, coordination',
      difficulty: 1,
      minPlayers: 4,
      maxPlayers: 16,
      durationMin: 8,
      intensity: 1,
      equipment: 'Balls, cones',
      pitchArea: '12x12',
      ageMin: 6,
      ageMax: 14,
      imageUrl: '/drills/warmup.png',
      coachId: demoCoach.id,
    },
    {
      id: 'warmup-tag-with-ball',
      name: 'Tag With Ball',
      description: 'Players dribble while trying to avoid tagged defenders.',
      objectives: 'Awareness, close control, fun activation',
      category: 'warmup',
      focusTags: 'dribbling, awareness, fun',
      difficulty: 1,
      minPlayers: 6,
      maxPlayers: 20,
      durationMin: 10,
      intensity: 1,
      equipment: 'Balls, bibs',
      pitchArea: '15x15',
      ageMin: 5,
      ageMax: 10,
      imageUrl: '/drills/warmup.png',
      coachId: demoCoach.id,
    },
    {
      id: 'warmup-passing-circle',
      name: 'Passing Circle Activation',
      description: 'Players pass around a circle with simple movement after each pass.',
      objectives: 'Passing rhythm, first touch, awareness',
      category: 'warmup',
      focusTags: 'passing, first touch, movement',
      difficulty: 1,
      minPlayers: 6,
      maxPlayers: 14,
      durationMin: 8,
      intensity: 1,
      equipment: 'Balls, cones',
      pitchArea: 'Circle 12m',
      ageMin: 7,
      ageMax: 16,
      imageUrl: '/drills/passing.png',
      coachId: demoCoach.id,
    },
    {
      id: 'warmup-dribble-zigzag',
      name: 'Dribble Zigzag',
      description: 'Players dribble through a zigzag cone pattern and accelerate out.',
      objectives: 'Close control, change of direction, coordination',
      category: 'warmup',
      focusTags: 'dribbling, turns, coordination',
      difficulty: 1,
      minPlayers: 4,
      maxPlayers: 14,
      durationMin: 8,
      intensity: 1,
      equipment: 'Balls, cones',
      pitchArea: '20x10',
      ageMin: 6,
      ageMax: 14,
      imageUrl: '/drills/dribbling.png',
      coachId: demoCoach.id,
    },

    // =========================
    // TECHNICAL
    // =========================
    {
      id: 'technical-triangle-passing',
      name: 'Triangle Passing',
      description: 'Players pass and move in triangle patterns with emphasis on angles.',
      objectives: 'Pass quality, movement after pass, body shape',
      category: 'technical',
      focusTags: 'passing, movement, first touch',
      difficulty: 2,
      minPlayers: 6,
      maxPlayers: 12,
      durationMin: 10,
      intensity: 1,
      equipment: 'Balls, cones',
      pitchArea: '15x15',
      ageMin: 8,
      ageMax: 18,
      imageUrl: '/drills/passing.png',
      coachId: demoCoach.id,
    },
    {
      id: 'technical-diamond-passing',
      name: 'Diamond Passing',
      description: 'Passing pattern in a diamond with timing and support angles.',
      objectives: 'Passing, timing, body orientation',
      category: 'technical',
      focusTags: 'passing, movement, body shape',
      difficulty: 2,
      minPlayers: 6,
      maxPlayers: 12,
      durationMin: 10,
      intensity: 1,
      equipment: 'Balls, cones',
      pitchArea: '18x18',
      ageMin: 8,
      ageMax: 18,
      imageUrl: '/drills/passing.png',
      coachId: demoCoach.id,
    },
    {
      id: 'technical-square-passing-rotation',
      name: 'Square Passing Rotation',
      description: 'Players pass around a square and rotate positions after each pass.',
      objectives: 'Passing quality, first touch, orientation',
      category: 'technical',
      focusTags: 'passing, first touch, movement, scanning',
      difficulty: 2,
      minPlayers: 6,
      maxPlayers: 12,
      durationMin: 10,
      intensity: 1,
      equipment: 'Balls, cones',
      pitchArea: '18x18',
      ageMin: 8,
      ageMax: 18,
      imageUrl: '/drills/passing.png',
      coachId: demoCoach.id,
    },
    {
      id: 'technical-y-passing-pattern',
      name: 'Y Passing Pattern',
      description: 'Players combine in a Y pattern with lay-offs and forward runs.',
      objectives: 'Combination play, timing, first touch',
      category: 'technical',
      focusTags: 'passing, combination play, movement',
      difficulty: 3,
      minPlayers: 6,
      maxPlayers: 12,
      durationMin: 12,
      intensity: 1,
      equipment: 'Balls, cones, mannequins',
      pitchArea: '20x15',
      ageMin: 10,
      ageMax: 18,
      imageUrl: '/drills/passing.png',
      coachId: demoCoach.id,
    },
    {
      id: 'technical-receiving-across-body',
      name: 'Receiving Across Body',
      description: 'Players receive on one side and play out on the opposite side under limited pressure.',
      objectives: 'Body shape, first touch, awareness',
      category: 'technical',
      focusTags: 'first touch, body shape, passing, scanning',
      difficulty: 2,
      minPlayers: 6,
      maxPlayers: 12,
      durationMin: 10,
      intensity: 2,
      equipment: 'Balls, cones, mannequins',
      pitchArea: '18x15',
      ageMin: 9,
      ageMax: 16,
      imageUrl: '/drills/passing.png',
      coachId: demoCoach.id,
    },
    {
      id: 'technical-first-touch-under-pressure',
      name: 'First Touch Under Pressure',
      description: 'Players receive while a defender applies controlled pressure.',
      objectives: 'First touch away from pressure, awareness',
      category: 'technical',
      focusTags: 'first touch, pressure, scanning, receiving',
      difficulty: 3,
      minPlayers: 6,
      maxPlayers: 12,
      durationMin: 12,
      intensity: 2,
      equipment: 'Balls, cones, bibs',
      pitchArea: '18x12',
      ageMin: 9,
      ageMax: 18,
      imageUrl: '/drills/passing.png',
      coachId: demoCoach.id,
    },
    {
      id: 'technical-directional-first-touch',
      name: 'Directional First Touch',
      description: 'Players receive and play their first touch into space before passing on.',
      objectives: 'Receiving angles, first touch, body orientation',
      category: 'technical',
      focusTags: 'first touch, receiving, body shape',
      difficulty: 2,
      minPlayers: 6,
      maxPlayers: 12,
      durationMin: 10,
      intensity: 1,
      equipment: 'Balls, cones',
      pitchArea: '15x12',
      ageMin: 8,
      ageMax: 18,
      imageUrl: '/drills/passing.png',
      coachId: demoCoach.id,
    },
    {
      id: 'technical-gates-passing',
      name: 'Passing Through Gates',
      description: 'Players pass through small cone gates while moving around the area.',
      objectives: 'Accuracy, first touch, pass timing',
      category: 'technical',
      focusTags: 'passing, first touch, accuracy',
      difficulty: 1,
      minPlayers: 4,
      maxPlayers: 16,
      durationMin: 10,
      intensity: 1,
      equipment: 'Balls, cones',
      pitchArea: '15x15',
      ageMin: 6,
      ageMax: 12,
      imageUrl: '/drills/passing.png',
      coachId: demoCoach.id,
    },
    {
      id: 'technical-wall-pass-pattern',
      name: 'Wall Pass Pattern',
      description: 'Players combine using wall passes and support runs.',
      objectives: 'Combination play, passing weight, timing',
      category: 'technical',
      focusTags: 'passing, combination play, movement',
      difficulty: 3,
      minPlayers: 6,
      maxPlayers: 12,
      durationMin: 12,
      intensity: 2,
      equipment: 'Balls, cones, mannequins',
      pitchArea: '20x15',
      ageMin: 10,
      ageMax: 18,
      imageUrl: '/drills/passing.png',
      coachId: demoCoach.id,
    },
    {
      id: 'technical-third-man-combination',
      name: 'Third Man Combination',
      description: 'Players use third-man runs to break lines and create forward play.',
      objectives: 'Third-man movement, timing, passing',
      category: 'technical',
      focusTags: 'passing, movement, decision making, attack',
      difficulty: 4,
      minPlayers: 6,
      maxPlayers: 14,
      durationMin: 14,
      intensity: 2,
      equipment: 'Balls, cones, mannequins',
      pitchArea: '25x20',
      ageMin: 12,
      ageMax: 18,
      imageUrl: '/drills/passing.png',
      coachId: demoCoach.id,
    },
    {
      id: 'technical-dribble-zones',
      name: 'Dribble Through Zones',
      description: 'Players dribble through marked zones using changes of pace and direction.',
      objectives: '1v1 ability, control, acceleration',
      category: 'technical',
      focusTags: 'dribbling, speed, coordination',
      difficulty: 2,
      minPlayers: 4,
      maxPlayers: 14,
      durationMin: 10,
      intensity: 2,
      equipment: 'Balls, cones',
      pitchArea: '20x12',
      ageMin: 7,
      ageMax: 14,
      imageUrl: '/drills/dribbling.png',
      coachId: demoCoach.id,
    },
    {
      id: 'technical-1v1-attacking-duel',
      name: '1v1 Attacking Duel',
      description: 'Players attack defenders in isolated 1v1 situations toward goal.',
      objectives: 'Confidence, dribbling, attacking intent',
      category: 'technical',
      focusTags: 'dribbling, confidence, attacking, 1v1',
      difficulty: 3,
      minPlayers: 4,
      maxPlayers: 10,
      durationMin: 10,
      intensity: 2,
      equipment: 'Balls, bibs, mini goals',
      pitchArea: '15x10',
      ageMin: 8,
      ageMax: 18,
      imageUrl: '/drills/dribbling.png',
      coachId: demoCoach.id,
    },
    {
      id: 'technical-turn-and-exit',
      name: 'Turn and Exit',
      description: 'Players perform specific turns and accelerate out of pressure.',
      objectives: 'Turning, balance, acceleration',
      category: 'technical',
      focusTags: 'dribbling, turns, speed',
      difficulty: 2,
      minPlayers: 4,
      maxPlayers: 12,
      durationMin: 8,
      intensity: 1,
      equipment: 'Balls, cones',
      pitchArea: '15x10',
      ageMin: 7,
      ageMax: 14,
      imageUrl: '/drills/dribbling.png',
      coachId: demoCoach.id,
    },
    {
      id: 'technical-double-move-1v1',
      name: 'Double Move 1v1',
      description: 'Players use body feints and double moves before attacking space.',
      objectives: 'Skill execution, confidence, 1v1 creativity',
      category: 'technical',
      focusTags: 'dribbling, 1v1, confidence',
      difficulty: 3,
      minPlayers: 4,
      maxPlayers: 10,
      durationMin: 10,
      intensity: 2,
      equipment: 'Balls, cones, mini goals',
      pitchArea: '18x12',
      ageMin: 9,
      ageMax: 18,
      imageUrl: '/drills/dribbling.png',
      coachId: demoCoach.id,
    },
    {
      id: 'technical-build-up-under-pressure',
      name: 'Build-Up Under Pressure',
      description: 'Players work on playing out from the back against an organized press.',
      objectives: 'Composure, passing options, decision making',
      category: 'technical',
      focusTags: 'build up, passing, positioning, decision making',
      difficulty: 5,
      minPlayers: 10,
      maxPlayers: 18,
      durationMin: 18,
      intensity: 3,
      equipment: 'Balls, bibs, mannequins, goals',
      pitchArea: 'Half pitch',
      ageMin: 13,
      ageMax: 18,
      imageUrl: '/drills/passing.png',
      coachId: demoCoach.id,
    },

    // =========================
    // POSSESSION
    // =========================
    {
      id: 'possession-rondo-4v1',
      name: 'Rondo 4v1',
      description: 'Four attackers keep possession against one defender in a small area.',
      objectives: 'Quick passing, support angles, first touch',
      category: 'possession',
      focusTags: 'possession, passing, first touch, scanning',
      difficulty: 2,
      minPlayers: 5,
      maxPlayers: 8,
      durationMin: 10,
      intensity: 1,
      equipment: 'Balls, cones, bibs',
      pitchArea: '10x10',
      ageMin: 8,
      ageMax: 18,
      imageUrl: '/drills/rondo.png',
      coachId: demoCoach.id,
    },
    {
      id: 'possession-rondo-5v2',
      name: 'Rondo 5v2',
      description: 'Five attackers circulate the ball against two defenders.',
      objectives: 'Scanning, passing speed, support',
      category: 'possession',
      focusTags: 'possession, passing, support, scanning',
      difficulty: 2,
      minPlayers: 7,
      maxPlayers: 10,
      durationMin: 10,
      intensity: 1,
      equipment: 'Balls, cones, bibs',
      pitchArea: '12x12',
      ageMin: 8,
      ageMax: 18,
      imageUrl: '/drills/rondo.png',
      coachId: demoCoach.id,
    },
    {
      id: 'possession-rondo-6v2',
      name: 'Rondo 6v2',
      description: 'Six attackers keep possession against two defenders.',
      objectives: 'Possession rhythm, decision making, pressing resistance',
      category: 'possession',
      focusTags: 'possession, passing, decision making, scanning',
      difficulty: 3,
      minPlayers: 8,
      maxPlayers: 10,
      durationMin: 12,
      intensity: 2,
      equipment: 'Balls, cones, bibs',
      pitchArea: '12x12',
      ageMin: 10,
      ageMax: 18,
      imageUrl: '/drills/rondo.png',
      coachId: demoCoach.id,
    },
    {
      id: 'possession-4v2-box',
      name: '4v2 Possession Box',
      description: 'Four attackers keep possession against two defenders in a grid.',
      objectives: 'Support angles, tempo, decision making',
      category: 'possession',
      focusTags: 'possession, passing, support, scanning',
      difficulty: 3,
      minPlayers: 6,
      maxPlayers: 10,
      durationMin: 12,
      intensity: 2,
      equipment: 'Balls, cones, bibs',
      pitchArea: '16x16',
      ageMin: 9,
      ageMax: 18,
      imageUrl: '/drills/possession.png',
      coachId: demoCoach.id,
    },
    {
      id: 'possession-5v5-game',
      name: '5v5 Possession Game',
      description: 'Small-sided possession game with emphasis on support and ball circulation.',
      objectives: 'Patience, support play, tempo',
      category: 'possession',
      focusTags: 'possession, passing, decision making, support',
      difficulty: 4,
      minPlayers: 10,
      maxPlayers: 12,
      durationMin: 15,
      intensity: 2,
      equipment: 'Balls, bibs',
      pitchArea: '25x20',
      ageMin: 10,
      ageMax: 18,
      imageUrl: '/drills/possession.png',
      coachId: demoCoach.id,
    },
    {
      id: 'possession-with-targets',
      name: 'Possession With Targets',
      description: 'Teams keep possession and score by finding target players.',
      objectives: 'Support, decision making, passing lines',
      category: 'possession',
      focusTags: 'possession, support, decision making, passing',
      difficulty: 3,
      minPlayers: 8,
      maxPlayers: 12,
      durationMin: 14,
      intensity: 2,
      equipment: 'Balls, cones, bibs',
      pitchArea: '24x18',
      ageMin: 10,
      ageMax: 18,
      imageUrl: '/drills/possession.png',
      coachId: demoCoach.id,
    },
    {
      id: 'positional-game-6v4',
      name: 'Positional Game 6v4',
      description: 'The team in possession works on spacing and playing through lines.',
      objectives: 'Positioning, scanning, support angles, breaking pressure',
      category: 'possession',
      focusTags: 'positioning, possession, scanning, passing',
      difficulty: 4,
      minPlayers: 10,
      maxPlayers: 14,
      durationMin: 16,
      intensity: 2,
      equipment: 'Balls, bibs, cones',
      pitchArea: '30x25',
      ageMin: 12,
      ageMax: 18,
      imageUrl: '/drills/possession.png',
      coachId: demoCoach.id,
    },
    {
      id: 'three-zone-possession',
      name: 'Three Zone Possession',
      description: 'Teams move the ball through zones to progress possession.',
      objectives: 'Circulation, support, playing through thirds',
      category: 'possession',
      focusTags: 'possession, support, positioning',
      difficulty: 3,
      minPlayers: 8,
      maxPlayers: 14,
      durationMin: 14,
      intensity: 2,
      equipment: 'Balls, bibs, cones',
      pitchArea: '30x20',
      ageMin: 10,
      ageMax: 18,
      imageUrl: '/drills/possession.png',
      coachId: demoCoach.id,
    },
    {
      id: 'switch-play-possession',
      name: 'Switch Play Possession',
      description: 'Teams keep possession and score by switching the ball to the opposite side.',
      objectives: 'Awareness, timing, support and switching play',
      category: 'possession',
      focusTags: 'possession, switching play, passing, scanning',
      difficulty: 4,
      minPlayers: 10,
      maxPlayers: 16,
      durationMin: 16,
      intensity: 2,
      equipment: 'Balls, bibs, cones',
      pitchArea: '35x25',
      ageMin: 12,
      ageMax: 18,
      imageUrl: '/drills/possession.png',
      coachId: demoCoach.id,
    },
    {
      id: 'half-turn-possession',
      name: 'Half Turn Possession',
      description: 'Players receive on the half turn and connect possession forward.',
      objectives: 'Receiving orientation, awareness, passing forward',
      category: 'possession',
      focusTags: 'possession, first touch, scanning, passing',
      difficulty: 3,
      minPlayers: 6,
      maxPlayers: 12,
      durationMin: 12,
      intensity: 2,
      equipment: 'Balls, cones, bibs',
      pitchArea: '18x18',
      ageMin: 10,
      ageMax: 18,
      imageUrl: '/drills/possession.png',
      coachId: demoCoach.id,
    },

    // =========================
    // FINISHING
    // =========================
    {
      id: 'finishing-cutbacks',
      name: 'Finishing From Cutbacks',
      description: 'Wide players serve cutbacks for arriving attackers.',
      objectives: 'Timing of runs, finishing, composure',
      category: 'finishing',
      focusTags: 'finishing, movement, timing',
      difficulty: 3,
      minPlayers: 6,
      maxPlayers: 12,
      durationMin: 12,
      intensity: 2,
      equipment: 'Balls, cones, goals',
      pitchArea: 'Penalty area',
      ageMin: 10,
      ageMax: 18,
      imageUrl: '/drills/finishing.png',
      coachId: demoCoach.id,
    },
    {
      id: 'finishing-first-time',
      name: 'First Time Finishing',
      description: 'Players attack service and finish first time from central and wide areas.',
      objectives: 'Timing, movement into the box, finishing technique',
      category: 'finishing',
      focusTags: 'finishing, timing, movement',
      difficulty: 3,
      minPlayers: 6,
      maxPlayers: 12,
      durationMin: 12,
      intensity: 2,
      equipment: 'Balls, cones, goals',
      pitchArea: 'Final third',
      ageMin: 10,
      ageMax: 18,
      imageUrl: '/drills/finishing.png',
      coachId: demoCoach.id,
    },
    {
      id: 'finishing-rebounds',
      name: 'Finishing Rebounds',
      description: 'Players follow shots and react quickly to rebounds around goal.',
      objectives: 'Reaction, composure, second actions',
      category: 'finishing',
      focusTags: 'finishing, reaction, movement',
      difficulty: 2,
      minPlayers: 4,
      maxPlayers: 10,
      durationMin: 10,
      intensity: 2,
      equipment: 'Balls, goals',
      pitchArea: 'Penalty area',
      ageMin: 9,
      ageMax: 18,
      imageUrl: '/drills/finishing.png',
      coachId: demoCoach.id,
    },
    {
      id: 'finishing-1v1-vs-keeper',
      name: '1v1 vs Keeper',
      description: 'Attackers drive at goal and finish against the goalkeeper.',
      objectives: 'Composure, speed, final decision',
      category: 'finishing',
      focusTags: 'finishing, confidence, attack, 1v1',
      difficulty: 3,
      minPlayers: 4,
      maxPlayers: 10,
      durationMin: 10,
      intensity: 2,
      equipment: 'Balls, goals, cones',
      pitchArea: '20x15',
      ageMin: 10,
      ageMax: 18,
      imageUrl: '/drills/finishing.png',
      coachId: demoCoach.id,
    },
    {
      id: 'finishing-under-pressure',
      name: 'Finishing Under Pressure',
      description: 'Attackers must finish quickly while recovering defenders apply pressure.',
      objectives: 'Composure, quick execution, finishing decisions',
      category: 'finishing',
      focusTags: 'finishing, pressure, decision making',
      difficulty: 4,
      minPlayers: 6,
      maxPlayers: 12,
      durationMin: 14,
      intensity: 3,
      equipment: 'Balls, cones, goals, bibs',
      pitchArea: 'Final third',
      ageMin: 12,
      ageMax: 18,
      imageUrl: '/drills/finishing.png',
      coachId: demoCoach.id,
    },
    {
      id: 'finishing-cross-and-finish',
      name: 'Cross and Finish',
      description: 'Wide players deliver crosses for attackers timing their runs into the box.',
      objectives: 'Crossing accuracy, finishing timing, box movement',
      category: 'finishing',
      focusTags: 'finishing, crossing, timing, movement',
      difficulty: 3,
      minPlayers: 6,
      maxPlayers: 14,
      durationMin: 14,
      intensity: 2,
      equipment: 'Balls, cones, goals',
      pitchArea: 'Final third',
      ageMin: 11,
      ageMax: 18,
      imageUrl: '/drills/finishing.png',
      coachId: demoCoach.id,
    },
    {
      id: 'finishing-overload-to-finish',
      name: 'Overload to Finish',
      description: 'Attacking unit creates overloads in the final third and finishes quickly.',
      objectives: 'Creating superiority, final pass, finishing',
      category: 'finishing',
      focusTags: 'finishing, overload, attack, passing',
      difficulty: 4,
      minPlayers: 8,
      maxPlayers: 14,
      durationMin: 14,
      intensity: 3,
      equipment: 'Balls, bibs, goals',
      pitchArea: 'Final third',
      ageMin: 12,
      ageMax: 18,
      imageUrl: '/drills/finishing.png',
      coachId: demoCoach.id,
    },
    {
      id: 'finishing-two-goal-break',
      name: 'Two Goal Break Finish',
      description: 'Players combine quickly and finish on one of two mini goals after a break.',
      objectives: 'Final pass, speed of attack, finishing choice',
      category: 'finishing',
      focusTags: 'finishing, attack, decision making',
      difficulty: 3,
      minPlayers: 6,
      maxPlayers: 12,
      durationMin: 12,
      intensity: 2,
      equipment: 'Balls, cones, mini goals',
      pitchArea: '25x18',
      ageMin: 10,
      ageMax: 18,
      imageUrl: '/drills/finishing.png',
      coachId: demoCoach.id,
    },

    // =========================
    // GAME
    // =========================
    {
      id: 'game-small-sided-3v3',
      name: 'Small-Sided 3v3',
      description: 'Simple free play game with lots of involvement and touches.',
      objectives: 'Enjoyment, game understanding, confidence',
      category: 'game',
      focusTags: 'game, confidence, decision making',
      difficulty: 1,
      minPlayers: 6,
      maxPlayers: 10,
      durationMin: 15,
      intensity: 2,
      equipment: 'Balls, bibs, mini goals',
      pitchArea: '20x15',
      ageMin: 5,
      ageMax: 8,
      imageUrl: '/drills/game.png',
      coachId: demoCoach.id,
    },
    {
      id: 'game-small-sided-4v4',
      name: 'Small-Sided Game 4v4',
      description: 'Fast 4v4 game with high involvement and many touches.',
      objectives: 'Decision making, positioning, transition',
      category: 'game',
      focusTags: 'game, decision making, positioning, transition',
      difficulty: 3,
      minPlayers: 8,
      maxPlayers: 12,
      durationMin: 15,
      intensity: 2,
      equipment: 'Balls, bibs, goals',
      pitchArea: '25x20',
      ageMin: 8,
      ageMax: 15,
      imageUrl: '/drills/game.png',
      coachId: demoCoach.id,
    },
    {
      id: 'game-small-sided-6v6',
      name: 'Small-Sided Game 6v6',
      description: 'Conditioned game encouraging realistic decisions and positioning.',
      objectives: 'Transfer to game, communication, positioning',
      category: 'game',
      focusTags: 'game, positioning, decision making, communication',
      difficulty: 4,
      minPlayers: 10,
      maxPlayers: 14,
      durationMin: 20,
      intensity: 3,
      equipment: 'Balls, bibs, goals',
      pitchArea: '40x30',
      ageMin: 10,
      ageMax: 18,
      imageUrl: '/drills/game.png',
      coachId: demoCoach.id,
    },
    {
      id: 'game-transition-4v4',
      name: 'Transition 4v4',
      description: 'Small-sided transition game with immediate attack after regaining possession.',
      objectives: 'Transition reactions, decision making, intensity',
      category: 'game',
      focusTags: 'transition, decision making, intensity',
      difficulty: 4,
      minPlayers: 8,
      maxPlayers: 10,
      durationMin: 15,
      intensity: 3,
      equipment: 'Balls, bibs, mini goals',
      pitchArea: '30x20',
      ageMin: 11,
      ageMax: 18,
      imageUrl: '/drills/game.png',
      coachId: demoCoach.id,
    },
    {
      id: 'game-2v1-attack-channel',
      name: '2v1 Attack Channel',
      description: 'Two attackers combine against one defender in a narrow channel.',
      objectives: 'Decision making, timing of pass, support play',
      category: 'game',
      focusTags: 'attack, passing, decision making, transition',
      difficulty: 2,
      minPlayers: 6,
      maxPlayers: 12,
      durationMin: 10,
      intensity: 2,
      equipment: 'Balls, bibs, mini goals',
      pitchArea: '20x10',
      ageMin: 8,
      ageMax: 14,
      imageUrl: '/drills/game.png',
      coachId: demoCoach.id,
    },
    {
      id: 'game-3v2-attack-to-goal',
      name: '3v2 Attack to Goal',
      description: 'Three attackers combine quickly against two defenders to finish.',
      objectives: 'Final third decisions, timing, finishing',
      category: 'game',
      focusTags: 'finishing, attack, decision making, passing',
      difficulty: 4,
      minPlayers: 5,
      maxPlayers: 12,
      durationMin: 12,
      intensity: 3,
      equipment: 'Balls, cones, goal',
      pitchArea: 'Half pitch',
      ageMin: 10,
      ageMax: 18,
      imageUrl: '/drills/game.png',
      coachId: demoCoach.id,
    },
    {
      id: 'game-counter-attack-wave',
      name: 'Counter Attack Wave',
      description: 'Teams attack quickly in waves after regaining possession.',
      objectives: 'Transition speed, final pass, decision making',
      category: 'game',
      focusTags: 'transition, attack, passing, decision making',
      difficulty: 4,
      minPlayers: 8,
      maxPlayers: 16,
      durationMin: 15,
      intensity: 3,
      equipment: 'Balls, cones, bibs, goals',
      pitchArea: 'Half pitch',
      ageMin: 12,
      ageMax: 18,
      imageUrl: '/drills/game.png',
      coachId: demoCoach.id,
    },
    {
      id: 'game-defensive-shape-6v6',
      name: 'Defensive Shape 6v6',
      description: 'Team works on compactness, distances and pressing cues in a conditioned game.',
      objectives: 'Defensive organization, communication, compactness',
      category: 'game',
      focusTags: 'defending, positioning, communication, pressing',
      difficulty: 4,
      minPlayers: 10,
      maxPlayers: 14,
      durationMin: 16,
      intensity: 3,
      equipment: 'Balls, bibs, cones, goals',
      pitchArea: '40x30',
      ageMin: 12,
      ageMax: 18,
      imageUrl: '/drills/game.png',
      coachId: demoCoach.id,
    },
    {
      id: 'game-pressing-triggers',
      name: 'Pressing Triggers Game',
      description: 'Conditioned game focusing on pressing cues and coordinated pressure.',
      objectives: 'Collective timing, pressing, communication',
      category: 'game',
      focusTags: 'pressing, transition, communication, decision making',
      difficulty: 5,
      minPlayers: 10,
      maxPlayers: 16,
      durationMin: 18,
      intensity: 3,
      equipment: 'Balls, bibs, goals',
      pitchArea: '45x35',
      ageMin: 13,
      ageMax: 18,
      imageUrl: '/drills/game.png',
      coachId: demoCoach.id,
    },
    {
      id: 'game-numbers-game-2v2',
      name: 'Numbers Game 2v2',
      description: 'Coach calls numbers and players enter for a quick 2v2 game.',
      objectives: 'Reaction, confidence, basic decisions',
      category: 'game',
      focusTags: 'reaction, confidence, decision making, game',
      difficulty: 2,
      minPlayers: 6,
      maxPlayers: 12,
      durationMin: 12,
      intensity: 2,
      equipment: 'Balls, bibs, mini goals',
      pitchArea: '20x15',
      ageMin: 6,
      ageMax: 10,
      imageUrl: '/drills/game.png',
      coachId: demoCoach.id,
    },
    {
      id: 'game-1v1-to-goal',
      name: '1v1 to Goal',
      description: 'Players compete in direct 1v1 situations toward mini goals.',
      objectives: 'Confidence, attacking, recovery defending',
      category: 'game',
      focusTags: '1v1, confidence, attack, defending',
      difficulty: 2,
      minPlayers: 4,
      maxPlayers: 10,
      durationMin: 10,
      intensity: 2,
      equipment: 'Balls, bibs, mini goals',
      pitchArea: '15x10',
      ageMin: 7,
      ageMax: 14,
      imageUrl: '/drills/game.png',
      coachId: demoCoach.id,
    },
    {
      id: 'game-possession-directional',
      name: 'Directional Possession Game',
      description: 'Possession game with clear attacking direction and transition moments.',
      objectives: 'Support, direction, pressing resistance',
      category: 'game',
      focusTags: 'possession, transition, decision making',
      difficulty: 4,
      minPlayers: 8,
      maxPlayers: 14,
      durationMin: 16,
      intensity: 3,
      equipment: 'Balls, bibs, goals',
      pitchArea: '35x25',
      ageMin: 11,
      ageMax: 18,
      imageUrl: '/drills/game.png',
      coachId: demoCoach.id,
    },
  ];

  for (const drill of drills) {
    await prisma.drill.upsert({
      where: { id: drill.id },
      update: drill,
      create: drill,
    });
  }

  console.log(`Seeded ${drills.length} drills successfully.`);
}

main()
  .catch((error) => {
    console.error('Seed failed:', error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });