import { revalidatePath } from "next/cache";

type AutoPlanInput = {
  teamId: string;
  coachId: string;
  date: string;
  durationMinutes: number;
  intensity: number;
  mainFocusTags?: string;
};

async function requestAutoPlan(data: AutoPlanInput) {
  const res = await fetch("http://localhost:3000/sessions/auto-plan", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(data),
    cache: "no-store",
  });
  if (!res.ok) {
    throw new Error("Failed to auto-plan session");
  }
  return res.json();
}

export default async function AutoPlanPage({
  params,
  searchParams,
}: {
  params: { id: string };
  searchParams: { focus?: string; duration?: string; intensity?: string };
}) {
  const duration = Number(searchParams.duration ?? 75);
  const intensity = Number(searchParams.intensity ?? 3);
  const focus = searchParams.focus ?? "";

  const today = new Date().toISOString();

  const draft = await requestAutoPlan({
    teamId: params.id,
    coachId: "demo-coach", // replace with real coach id when auth is added
    date: today,
    durationMinutes: duration,
    intensity,
    mainFocusTags: focus,
  });

  revalidatePath(`/teams/${params.id}`);

  return (
    <main style={{ padding: "2rem", maxWidth: 960, margin: "0 auto" }}>
      <h1>Auto-planned session</h1>
      <p>
        This is a draft generated by the rule-based planner. Later you can
        refine it with AI and save it.
      </p>
      <pre
        style={{
          marginTop: "1.5rem",
          padding: "1rem",
          borderRadius: 8,
          border: "1px solid #ddd",
          background: "#fafafa",
          fontSize: 13,
          overflowX: "auto",
        }}
      >
        {JSON.stringify(draft, null, 2)}
      </pre>
    </main>
  );
}

